import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Create 10 dummy doctors
  await prisma.doctor.createMany({
    data: [
      {
        name: 'Dr. Alice Smith',
        profileImageUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
        degrees: 'MBBS, MD',
        specialization: 'Cardiologist',
        experienceYears: 10,
        consultationFee: 500,
        noBookingFees: true,
        location: 'Mumbai',
        clinicName: 'Heart Care Clinic',
        availableAt: new Date('2024-07-01T10:00:00Z'),
        rating: 4.7,
        patientsTreated: 1500,
        modesOfConsult: ['PHYSICAL', 'ONLINE'],
        languages: ['ENGLISH', 'HINDI'],
        facilities: ['APOLLO_HOSPITAL'],
      },
      {
        name: 'Dr. Bob Johnson',
        profileImageUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
        degrees: 'MBBS, DNB General Medicine',
        specialization: 'General Physician',
        experienceYears: 8,
        consultationFee: 300,
        noBookingFees: false,
        location: 'Delhi',
        clinicName: 'City Health Clinic',
        availableAt: new Date('2024-07-02T11:00:00Z'),
        rating: 4.3,
        patientsTreated: 1200,
        modesOfConsult: ['PHYSICAL'],
        languages: ['ENGLISH'],
        facilities: ['OTHER_CLINICS'],
      },
      {
        name: 'Dr. Charlie Lee',
        profileImageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
        degrees: 'MBBS, MS',
        specialization: 'Orthopedic Surgeon',
        experienceYears: 12,
        consultationFee: 700,
        noBookingFees: true,
        location: 'Bangalore',
        clinicName: 'Ortho Plus',
        availableAt: new Date('2024-07-03T09:30:00Z'),
        rating: 4.8,
        patientsTreated: 2000,
        modesOfConsult: ['ONLINE'],
        languages: ['ENGLISH', 'TELUGU'],
        facilities: ['APOLLO_HOSPITAL'],
      },
      {
        name: 'Dr. Diana Patel',
        profileImageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
        degrees: 'MBBS, DGO',
        specialization: 'Gynecologist',
        experienceYears: 9,
        consultationFee: 400,
        noBookingFees: false,
        location: 'Hyderabad',
        clinicName: 'Women Care Center',
        availableAt: new Date('2024-07-04T14:00:00Z'),
        rating: 4.6,
        patientsTreated: 1300,
        modesOfConsult: ['PHYSICAL', 'ONLINE'],
        languages: ['ENGLISH', 'HINDI', 'TELUGU'],
        facilities: ['OTHER_CLINICS'],
      },
      {
        name: 'Dr. Edward Kim',
        profileImageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
        degrees: 'MBBS, DM',
        specialization: 'Neurologist',
        experienceYears: 15,
        consultationFee: 800,
        noBookingFees: true,
        location: 'Chennai',
        clinicName: 'Neuro Clinic',
        availableAt: new Date('2024-07-05T16:00:00Z'),
        rating: 4.9,
        patientsTreated: 2500,
        modesOfConsult: ['PHYSICAL'],
        languages: ['ENGLISH'],
        facilities: ['APOLLO_HOSPITAL'],
      },
      {
        name: 'Dr. Fiona Dsouza',
        profileImageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
        degrees: 'MBBS, MS',
        specialization: 'ENT Specialist',
        experienceYears: 7,
        consultationFee: 350,
        noBookingFees: false,
        location: 'Pune',
        clinicName: 'Ear Nose Throat Clinic',
        availableAt: new Date('2024-07-06T12:00:00Z'),
        rating: 4.2,
        patientsTreated: 900,
        modesOfConsult: ['ONLINE'],
        languages: ['ENGLISH', 'HINDI'],
        facilities: ['OTHER_CLINICS'],
      },
      {
        name: 'Dr. George Thomas',
        profileImageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
        degrees: 'MBBS, MD',
        specialization: 'Dermatologist',
        experienceYears: 11,
        consultationFee: 600,
        noBookingFees: true,
        location: 'Kolkata',
        clinicName: 'Skin Care Clinic',
        availableAt: new Date('2024-07-07T15:00:00Z'),
        rating: 4.5,
        patientsTreated: 1700,
        modesOfConsult: ['PHYSICAL', 'ONLINE'],
        languages: ['ENGLISH'],
        facilities: ['APOLLO_HOSPITAL'],
      },
      {
        name: 'Dr. Hannah Mehra',
        profileImageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
        degrees: 'MBBS, DNB',
        specialization: 'Pediatrician',
        experienceYears: 6,
        consultationFee: 450,
        noBookingFees: false,
        location: 'Ahmedabad',
        clinicName: 'Child Health Clinic',
        availableAt: new Date('2024-07-08T13:00:00Z'),
        rating: 4.4,
        patientsTreated: 1100,
        modesOfConsult: ['PHYSICAL'],
        languages: ['ENGLISH', 'HINDI'],
        facilities: ['OTHER_CLINICS'],
      },
      {
        name: 'Dr. Ian Kapoor',
        profileImageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
        degrees: 'MBBS, MS',
        specialization: 'Ophthalmologist',
        experienceYears: 13,
        consultationFee: 550,
        noBookingFees: true,
        location: 'Coimbatore',
        clinicName: 'Vision Care',
        availableAt: new Date('2024-07-09T10:30:00Z'),
        rating: 4.6,
        patientsTreated: 1800,
        modesOfConsult: ['ONLINE'],
        languages: ['ENGLISH', 'TELUGU'],
        facilities: ['APOLLO_HOSPITAL'],
      },
      {
        name: 'Dr. Julia Rao',
        profileImageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
        degrees: 'MBBS, MD',
        specialization: 'Psychiatrist',
        experienceYears: 9,
        consultationFee: 650,
        noBookingFees: false,
        location: 'Lucknow',
        clinicName: 'Mind Wellness Center',
        availableAt: new Date('2024-07-10T17:00:00Z'),
        rating: 4.7,
        patientsTreated: 1400,
        modesOfConsult: ['PHYSICAL', 'ONLINE'],
        languages: ['ENGLISH', 'HINDI'],
        facilities: ['OTHER_CLINICS'],
      },
    ],
  });

  console.log('Seeding completed.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
